In [1]:
import tensorflow as tf
print(tf.__version__)

1.10.0


In [2]:
hello  = tf.constant('Hello ')

In [3]:
world = tf.constant('World')

In [4]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [5]:
with tf.Session() as sess:    
    
    result = sess.run(hello+world)

In [6]:
result

b'Hello World'

In [7]:
a = tf.constant(10)
b = tf.constant(20)

In [8]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [10]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [9]:
with tf.Session() as sess:
    
    result = sess.run(a+b)

In [11]:
result

30

In [12]:
const = tf.constant(10)

In [13]:
fill_mat = tf.fill((4,4),10)

In [14]:
myzerso = tf.zeros((4,4))

In [17]:
ones = tf.ones((4,4))

In [16]:
myrandom = tf.random_normal((4,4),mean=0,stddev=1)

In [15]:
myrandom = tf.random_uniform((4,4),minval=0,maxval=1)

In [18]:
my_ops = [const,fill_mat,myzerso]

In [19]:
sess = tf.InteractiveSession()

In [22]:
for op in my_ops:
    
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]




In [24]:
a = tf.constant([[1,2],[3,4]])

In [25]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [26]:
b = tf.constant([[10],[100]])

In [27]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [28]:
result = tf.matmul(a,b)

In [29]:
sess.run(result)

array([[210],
       [430]])

In [30]:
result.eval()

array([[210],
       [430]])

# TF Graphs

In [32]:
n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1+n2

In [33]:
with tf.Session() as sess:
    result = sess.run(n3)

In [34]:
print(result)

3


In [35]:
print(n3)

Tensor("add_4:0", shape=(), dtype=int32)


In [36]:
print(tf.get_default_graph)

<function get_default_graph at 0x000002D2D29A0950>


In [37]:
g = tf.Graph()

In [38]:
print(g)

In [39]:
graph_one = tf.get_default_graph()

In [40]:
graph_two = tf.Graph()

In [41]:
print(graph_one)

In [42]:
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

True


In [43]:
print(graph_two is tf.get_default_graph())

False


# Variables and Placeholders

In [45]:
sess = tf.InteractiveSession()

C:\Users\AI\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [46]:
my_tensor = tf.random_uniform((4,4),0,1)

In [47]:
my_var = tf.Variable(initial_value=my_tensor)

In [48]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [55]:
#sess.run(my_var)

In [51]:
init = tf.global_variables_initializer()

In [52]:
sess.run(init)

In [54]:
sess.run(my_var)

array([[0.3197924 , 0.44552088, 0.05314112, 0.68209696],
       [0.61503005, 0.18375182, 0.4595127 , 0.2455678 ],
       [0.4890157 , 0.82356596, 0.8527334 , 0.5490029 ],
       [0.97506607, 0.44475722, 0.992172  , 0.22505367]], dtype=float32)

In [57]:
ph = tf.placeholder(tf.float32,(4,4),name ='ph')

In [59]:
print(ph)

Tensor("ph:0", shape=(4, 4), dtype=float32)
